### ISSUE TITLE
Component list is not sorted in edit mode sometimes

### ISSUE THREAD

**Issue by kreetrapper** [clarin-eric/component-registry-front-end#69]
In editing mode, when I add another component, the list of available components is ordered at first, but when I then switch from 'public' to my group (MPI LAT), the components are no longer sorted. See attached screenshot.

![unsorted-components](https://cloud.githubusercontent.com/assets/8858235/17404985/0c8bdd94-5a5e-11e6-9403-17a6fdd5c23c.png)

**Comment by twagoo** [comment]
Still could not reproduce the issue precisely, but ensuring a default sort order for all spaces in the back end and the added option to manually sort in the editor should at least mitigate this issue sufficiently.

Note: I could reproduce the converse scenario: public items were nicely sorted, but team items were not. This was caused by a lack of sorting in the back end, which has been resolved (see above).
